// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_COMP_UILABELTIME_H
#define _UI_COMP_UILABELTIME_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT uiLabelTime
#define UI_COMP_UILABELTIME_UILABELTIME 0
#define _UI_COMP_UILABELTIME_NUM 1
lv_obj_t * ui_uiLabelTime_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
