// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT uiLabelTime

lv_obj_t * ui_uiLabelTime_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_uiLabelTime;
    cui_uiLabelTime = lv_label_create(comp_parent);
    lv_obj_set_width(cui_uiLabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_uiLabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_uiLabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(cui_uiLabelTime, "text");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_UILABELTIME_NUM);
    children[UI_COMP_UILABELTIME_UILABELTIME] = cui_uiLabelTime;
    lv_obj_add_event_cb(cui_uiLabelTime, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_uiLabelTime, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_uiLabelTime_create_hook(cui_uiLabelTime);
    return cui_uiLabelTime;
}

