// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Background2;
extern lv_obj_t * ui_PanelMenu2;
extern void ui_event_MenuHome2(lv_event_t * e);
extern lv_obj_t * ui_MenuHome2;
extern lv_obj_t * ui_MenuWeather2;
extern void ui_event_MenuHeartRate2(lv_event_t * e);
extern lv_obj_t * ui_MenuHeartRate2;
extern void ui_event_MenuAlerts2(lv_event_t * e);
extern lv_obj_t * ui_MenuAlerts2;
extern void ui_event_MenuSettings2(lv_event_t * e);
extern lv_obj_t * ui_MenuSettings2;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

