// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_PanelMenu;
extern lv_obj_t * ui_MenuHome;
extern void ui_event_MenuWeather(lv_event_t * e);
extern lv_obj_t * ui_MenuWeather;
extern void ui_event_MenuHeartRate(lv_event_t * e);
extern lv_obj_t * ui_MenuHeartRate;
extern void ui_event_MenuAlerts(lv_event_t * e);
extern lv_obj_t * ui_MenuAlerts;
extern void ui_event_MenuSettings(lv_event_t * e);
extern lv_obj_t * ui_MenuSettings;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

