// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: UI_Weather

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Background2;
extern lv_obj_t * ui_PanelMenu2;
extern void ui_event_MenuHome2(lv_event_t * e);
extern lv_obj_t * ui_MenuHome2;
extern lv_obj_t * ui_MenuWeather2;
extern void ui_event_MenuHeartRate2(lv_event_t * e);
extern lv_obj_t * ui_MenuHeartRate2;
extern void ui_event_MenuAlerts2(lv_event_t * e);
extern lv_obj_t * ui_MenuAlerts2;
extern void ui_event_MenuSettings2(lv_event_t * e);
extern lv_obj_t * ui_MenuSettings2;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_LabelTime2;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_PanelWeather;
extern lv_obj_t * ui_PanelSummary;
extern lv_obj_t * ui_PanelPosition;
extern lv_obj_t * ui_ImagePosition;
extern lv_obj_t * ui_LabelPosition;
extern lv_obj_t * ui_ImageWeather;
extern lv_obj_t * ui_LabelWeatherDesc;
extern lv_obj_t * ui_PanelTemp;
extern lv_obj_t * ui_LabelTempMinNUM;
extern lv_obj_t * ui_LabelConnector;
extern lv_obj_t * ui_LabelTempMaxNUM;
extern lv_obj_t * ui_LabelTempUnit;
extern lv_obj_t * ui_PanelDetails;
extern lv_obj_t * ui_PanelRainFall;
extern lv_obj_t * ui_LabelRainFallTitle;
extern lv_obj_t * ui_LabelRainFallVal;
extern lv_obj_t * ui_LabelRainFallUnit;
extern lv_obj_t * ui_PanelRainProb;
extern lv_obj_t * ui_LabelRainProbTitle;
extern lv_obj_t * ui_LabelRainProbVal;
extern lv_obj_t * ui_LabelRainProbUnit;
extern lv_obj_t * ui_PanelWindDirAngle;
extern lv_obj_t * ui_LabelWindDirTitle;
extern lv_obj_t * ui_LabelWindDir;
extern lv_obj_t * ui_LabelWindAngleTitle;
extern lv_obj_t * ui_LabelWindAngle;
extern lv_obj_t * ui_PanelWindSpeed;
extern lv_obj_t * ui_LabelWindSpeedTitle;
extern lv_obj_t * ui_LabelWindSpeedVal;
extern lv_obj_t * ui_LabelWindSpeedUnit;
extern lv_obj_t * ui_PanelWindLevel;
extern lv_obj_t * ui_LabelWindLevelTitle;
extern lv_obj_t * ui_LabelWindLevelVal;
extern lv_obj_t * ui_PanelHum;
extern lv_obj_t * ui_LabelHumTitle;
extern lv_obj_t * ui_LabelHumVal;
extern lv_obj_t * ui_LabelHumUnit;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_PanelWeather1;
extern lv_obj_t * ui_PanelSummary1;
extern lv_obj_t * ui_PanelPosition1;
extern lv_obj_t * ui_ImagePosition1;
extern lv_obj_t * ui_LabelPosition1;
extern lv_obj_t * ui_ImageWeather1;
extern lv_obj_t * ui_LabelWeatherDesc1;
extern lv_obj_t * ui_PanelTemp1;
extern lv_obj_t * ui_LabelTempMinNUM1;
extern lv_obj_t * ui_LabelConnector1;
extern lv_obj_t * ui_LabelTempMaxNUM1;
extern lv_obj_t * ui_LabelTempUnit1;
extern lv_obj_t * ui_PanelDetails1;
extern lv_obj_t * ui_PanelRainFall1;
extern lv_obj_t * ui_LabelRainFallTitle1;
extern lv_obj_t * ui_LabelRainFallVal1;
extern lv_obj_t * ui_LabelRainFallUnit1;
extern lv_obj_t * ui_PanelRainProb1;
extern lv_obj_t * ui_LabelRainProbTitle1;
extern lv_obj_t * ui_LabelRainProbVal1;
extern lv_obj_t * ui_LabelRainProbUnit1;
extern lv_obj_t * ui_PanelWindDirAngle1;
extern lv_obj_t * ui_LabelWindDirTitle1;
extern lv_obj_t * ui_LabelWindDir1;
extern lv_obj_t * ui_LabelWindAngleTitle1;
extern lv_obj_t * ui_LabelWindAngle1;
extern lv_obj_t * ui_PanelWindSpeed1;
extern lv_obj_t * ui_LabelWindSpeedTitle1;
extern lv_obj_t * ui_LabelWindSpeedVal1;
extern lv_obj_t * ui_LabelWindSpeedUnit1;
extern lv_obj_t * ui_PanelWindLevel1;
extern lv_obj_t * ui_LabelWindLevelTitle1;
extern lv_obj_t * ui_LabelWindLevelVal1;
extern lv_obj_t * ui_PanelHum1;
extern lv_obj_t * ui_LabelHumTitle1;
extern lv_obj_t * ui_LabelHumVal1;
extern lv_obj_t * ui_LabelHumUnit1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_PanelWeather2;
extern lv_obj_t * ui_PanelSummary2;
extern lv_obj_t * ui_PanelPosition2;
extern lv_obj_t * ui_ImagePosition2;
extern lv_obj_t * ui_LabelPosition2;
extern lv_obj_t * ui_ImageWeather2;
extern lv_obj_t * ui_LabelWeatherDesc2;
extern lv_obj_t * ui_PanelTemp2;
extern lv_obj_t * ui_LabelTempMinNUM2;
extern lv_obj_t * ui_LabelConnector2;
extern lv_obj_t * ui_LabelTempMaxNUM2;
extern lv_obj_t * ui_LabelTempUnit2;
extern lv_obj_t * ui_PanelDetails2;
extern lv_obj_t * ui_PanelRainFall2;
extern lv_obj_t * ui_LabelRainFallTitle2;
extern lv_obj_t * ui_LabelRainFallVal2;
extern lv_obj_t * ui_LabelRainFallUnit2;
extern lv_obj_t * ui_PanelRainProb2;
extern lv_obj_t * ui_LabelRainProbTitle2;
extern lv_obj_t * ui_LabelRainProbVal2;
extern lv_obj_t * ui_LabelRainProbUnit2;
extern lv_obj_t * ui_PanelWindDirAngle2;
extern lv_obj_t * ui_LabelWindDirTitle2;
extern lv_obj_t * ui_LabelWindDir2;
extern lv_obj_t * ui_LabelWindAngleTitle2;
extern lv_obj_t * ui_LabelWindAngle2;
extern lv_obj_t * ui_PanelWindSpeed2;
extern lv_obj_t * ui_LabelWindSpeedTitle2;
extern lv_obj_t * ui_LabelWindSpeedVal2;
extern lv_obj_t * ui_LabelWindSpeedUnit2;
extern lv_obj_t * ui_PanelWindLevel2;
extern lv_obj_t * ui_LabelWindLevelTitle2;
extern lv_obj_t * ui_LabelWindLevelVal2;
extern lv_obj_t * ui_PanelHum2;
extern lv_obj_t * ui_LabelHumTitle2;
extern lv_obj_t * ui_LabelHumVal2;
extern lv_obj_t * ui_LabelHumUnit2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

