// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Background4 = NULL;
lv_obj_t * ui_PanelMenu4 = NULL;
lv_obj_t * ui_MenuHome4 = NULL;
lv_obj_t * ui_MenuWeather4 = NULL;
lv_obj_t * ui_MenuHeartRate4 = NULL;
lv_obj_t * ui_MenuAlerts4 = NULL;
lv_obj_t * ui_MenuSettings4 = NULL;
// event funtions
void ui_event_MenuHome4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_MenuWeather4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_MenuHeartRate4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_MenuSettings4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen5_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background4 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Background4, &ui_img_background_image_png);
    lv_obj_set_width(ui_Background4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Background4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Background4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Background4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMenu4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelMenu4, 72);
    lv_obj_set_height(ui_PanelMenu4, 320);
    lv_obj_set_flex_flow(ui_PanelMenu4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelMenu4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PanelMenu4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMenu4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelMenu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelMenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuHome4 = lv_image_create(ui_PanelMenu4);
    lv_image_set_src(ui_MenuHome4, &ui_img_home_active_page_png);
    lv_obj_set_width(ui_MenuHome4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuHome4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuHome4, -70);
    lv_obj_set_y(ui_MenuHome4, -15);
    lv_obj_add_flag(ui_MenuHome4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuHome4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuHome4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuWeather4 = lv_image_create(ui_PanelMenu4);
    lv_image_set_src(ui_MenuWeather4, &ui_img_weather_active_page_png);
    lv_obj_set_width(ui_MenuWeather4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuWeather4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuWeather4, -30);
    lv_obj_set_y(ui_MenuWeather4, 94);
    lv_obj_add_flag(ui_MenuWeather4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuWeather4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuWeather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuHeartRate4 = lv_image_create(ui_PanelMenu4);
    lv_image_set_src(ui_MenuHeartRate4, &ui_img_heart_rate_active_page_png);
    lv_obj_set_width(ui_MenuHeartRate4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuHeartRate4, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuHeartRate4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuHeartRate4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuHeartRate4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuAlerts4 = lv_image_create(ui_PanelMenu4);
    lv_image_set_src(ui_MenuAlerts4, &ui_img_alerts_active_page_png);
    lv_obj_set_width(ui_MenuAlerts4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuAlerts4, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuAlerts4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuAlerts4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuSettings4 = lv_image_create(ui_PanelMenu4);
    lv_image_set_src(ui_MenuSettings4, &ui_img_settings_active_page_png);
    lv_obj_set_width(ui_MenuSettings4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSettings4, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuSettings4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuSettings4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuSettings4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuHome4, ui_event_MenuHome4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuWeather4, ui_event_MenuWeather4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuHeartRate4, ui_event_MenuHeartRate4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuSettings4, ui_event_MenuSettings4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Background4 = NULL;
    ui_PanelMenu4 = NULL;
    ui_MenuHome4 = NULL;
    ui_MenuWeather4 = NULL;
    ui_MenuHeartRate4 = NULL;
    ui_MenuAlerts4 = NULL;
    ui_MenuSettings4 = NULL;

}
