// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Background5;
extern lv_obj_t * ui_PanelMenu5;
extern void ui_event_MenuHome5(lv_event_t * e);
extern lv_obj_t * ui_MenuHome5;
extern void ui_event_MenuWeather5(lv_event_t * e);
extern lv_obj_t * ui_MenuWeather5;
extern void ui_event_MenuHeartRate5(lv_event_t * e);
extern lv_obj_t * ui_MenuHeartRate5;
extern void ui_event_MenuAlerts5(lv_event_t * e);
extern lv_obj_t * ui_MenuAlerts5;
extern lv_obj_t * ui_MenuSettings5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

