// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Background4;
extern lv_obj_t * ui_PanelMenu4;
extern void ui_event_MenuHome4(lv_event_t * e);
extern lv_obj_t * ui_MenuHome4;
extern void ui_event_MenuWeather4(lv_event_t * e);
extern lv_obj_t * ui_MenuWeather4;
extern void ui_event_MenuHeartRate4(lv_event_t * e);
extern lv_obj_t * ui_MenuHeartRate4;
extern lv_obj_t * ui_MenuAlerts4;
extern void ui_event_MenuSettings4(lv_event_t * e);
extern lv_obj_t * ui_MenuSettings4;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_LabelTime3;
extern lv_obj_t * ui_RollerMin;
extern lv_obj_t * ui_PanelAlarmPopup1;
extern void ui_event_SwitchAlarm(lv_event_t * e);
extern lv_obj_t * ui_SwitchAlarm;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_PanelAlarmPopup;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

