// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Background3;
extern lv_obj_t * ui_PanelMenu3;
extern void ui_event_MenuHome3(lv_event_t * e);
extern lv_obj_t * ui_MenuHome3;
extern void ui_event_MenuWeather3(lv_event_t * e);
extern lv_obj_t * ui_MenuWeather3;
extern lv_obj_t * ui_MenuHeartRate3;
extern void ui_event_MenuAlerts3(lv_event_t * e);
extern lv_obj_t * ui_MenuAlerts3;
extern void ui_event_MenuSettings3(lv_event_t * e);
extern lv_obj_t * ui_MenuSettings3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

