// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Background2 = NULL;
lv_obj_t * ui_PanelMenu2 = NULL;
lv_obj_t * ui_MenuHome2 = NULL;
lv_obj_t * ui_MenuWeather2 = NULL;
lv_obj_t * ui_MenuHeartRate2 = NULL;
lv_obj_t * ui_MenuAlerts2 = NULL;
lv_obj_t * ui_MenuSettings2 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_LabelTime2 = NULL;
// event funtions
void ui_event_MenuHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_MenuHeartRate2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_MenuAlerts2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_MenuSettings2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen5_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background2 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Background2, &ui_img_background_image_png);
    lv_obj_set_width(ui_Background2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Background2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Background2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Background2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMenu2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelMenu2, 72);
    lv_obj_set_height(ui_PanelMenu2, 320);
    lv_obj_set_flex_flow(ui_PanelMenu2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelMenu2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PanelMenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMenu2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuHome2 = lv_image_create(ui_PanelMenu2);
    lv_image_set_src(ui_MenuHome2, &ui_img_home_active_page_png);
    lv_obj_set_width(ui_MenuHome2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuHome2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuHome2, -70);
    lv_obj_set_y(ui_MenuHome2, -15);
    lv_obj_add_flag(ui_MenuHome2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuHome2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuHome2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuWeather2 = lv_image_create(ui_PanelMenu2);
    lv_image_set_src(ui_MenuWeather2, &ui_img_weather_active_page_png);
    lv_obj_set_width(ui_MenuWeather2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuWeather2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuWeather2, -30);
    lv_obj_set_y(ui_MenuWeather2, 94);
    lv_obj_add_flag(ui_MenuWeather2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuWeather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuHeartRate2 = lv_image_create(ui_PanelMenu2);
    lv_image_set_src(ui_MenuHeartRate2, &ui_img_heart_rate_active_page_png);
    lv_obj_set_width(ui_MenuHeartRate2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuHeartRate2, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuHeartRate2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuHeartRate2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuHeartRate2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuAlerts2 = lv_image_create(ui_PanelMenu2);
    lv_image_set_src(ui_MenuAlerts2, &ui_img_alerts_active_page_png);
    lv_obj_set_width(ui_MenuAlerts2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuAlerts2, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuAlerts2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuAlerts2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuAlerts2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSettings2 = lv_image_create(ui_PanelMenu2);
    lv_image_set_src(ui_MenuSettings2, &ui_img_settings_active_page_png);
    lv_obj_set_width(ui_MenuSettings2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSettings2, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_MenuSettings2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MenuSettings2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuSettings2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel12, 388);
    lv_obj_set_height(ui_Panel12, 22);
    lv_obj_set_x(ui_Panel12, 82);
    lv_obj_set_y(ui_Panel12, 0);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime2 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_LabelTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelTime2, "00:00:00");
    lv_obj_set_style_text_color(ui_LabelTime2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime2, &ui_font_RobotoMonoBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuHome2, ui_event_MenuHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuHeartRate2, ui_event_MenuHeartRate2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuAlerts2, ui_event_MenuAlerts2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuSettings2, ui_event_MenuSettings2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Background2 = NULL;
    ui_PanelMenu2 = NULL;
    ui_MenuHome2 = NULL;
    ui_MenuWeather2 = NULL;
    ui_MenuHeartRate2 = NULL;
    ui_MenuAlerts2 = NULL;
    ui_MenuSettings2 = NULL;
    ui_Panel12 = NULL;
    ui_LabelTime2 = NULL;

}
