// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_image_png);    // assets/background_image.png
LV_IMG_DECLARE(ui_img_home_active_page_png);    // assets/home_active_page.png
LV_IMG_DECLARE(ui_img_weather_active_page_png);    // assets/weather_active_page.png
LV_IMG_DECLARE(ui_img_heart_rate_active_page_png);    // assets/heart_rate_active_page.png
LV_IMG_DECLARE(ui_img_alerts_active_page_png);    // assets/alerts_active_page.png
LV_IMG_DECLARE(ui_img_settings_active_page_png);    // assets/settings_active_page.png
LV_IMG_DECLARE(ui_img_light_intensity_png);    // assets/light_intensity.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_heart_rate_png);    // assets/heart_rate.png
LV_IMG_DECLARE(ui_img_spo2_png);    // assets/spo2.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png

// FONTS
LV_FONT_DECLARE(ui_font_RobotoMonoBold14);
LV_FONT_DECLARE(ui_font_RobotoMonoBold16);
LV_FONT_DECLARE(ui_font_RobotoMonoBold26);
LV_FONT_DECLARE(ui_font_RobotoMonoBold40);
LV_FONT_DECLARE(ui_font_SourceHanSansBold12);
LV_FONT_DECLARE(ui_font_SourceHanSansBold26);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
