// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

#include "app_alarm_notify.h"
#include "app_voice_service.h"

void btn_help_cb(lv_event_t *e)
{

	/* 释放信号量，唤醒报警任务 */
	if (xAlarmSemaphore != NULL)
	{
		xSemaphoreGive(xAlarmSemaphore);
	}

	/* 用队列向语音任务发送跌倒报警的通知 */
	if (xVoiceQueue != NULL)
	{
		Voice_Msg_Type_t msg = MSG_VOICE_HELP_ALARM;
		xQueueSend(xVoiceQueue, &msg, 0); /* 跨任务投递消息 */
	}
}
