// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_alarm_switch_changed(lv_event_t * e);
void ui_event_alarm_confirm(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
