// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

#include "pal_log.h"

#include "app_rtc_alarm.h"

void ui_event_alarm_confirm(lv_event_t *e)
{
    /* 隐藏弹窗 */
    lv_obj_add_flag(ui_PanelAlarmPopup, LV_OBJ_FLAG_HIDDEN);

    /* 重置闹钟活动状态 */
    g_user_alarm.is_active = false;
}

void ui_event_alarm_switch_changed(lv_event_t *e)
{
    lv_obj_t *sw = lv_event_get_target(e);

    if (lv_obj_has_state(sw, LV_STATE_CHECKED))
    {
        /* 开关时同步滚轮数值 */
        g_user_alarm.hour = (uint8_t)lv_roller_get_selected(ui_RollerHour);
        g_user_alarm.minute = (uint8_t)lv_roller_get_selected(ui_RollerMin);

        g_user_alarm.is_enabled = true;
        g_user_alarm.is_active = false; /* 清除之前的触发标记 */

        PAL_LOG(PAL_LOG_LEVEL_INFO, "Alarm Set for %02d:%02d and Enabled",
                g_user_alarm.hour, g_user_alarm.minute);
    }
    else
    {
        g_user_alarm.is_enabled = false;
        g_user_alarm.is_active = false;
        PAL_LOG(PAL_LOG_LEVEL_INFO, "Alarm Disabled");
    }
}
